# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: prime.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'prime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bprime.proto\x12\x05prime\"\x1e\n\x0cPrimeRequest\x12\x0e\n\x06number\x18\x01 \x01(\x03\"2\n\rPrimeResponse\x12\x10\n\x08is_prime\x18\x01 \x01(\x08\x12\x0f\n\x07\x66\x61\x63tors\x18\x02 \x03(\x03\"\x1e\n\x11\x46irstPrimeRequest\x12\t\n\x01n\x18\x01 \x01(\x03\"$\n\x12\x46irstPrimeResponse\x12\x0e\n\x06primes\x18\x01 \x03(\x03\"+\n\x0fIntervalRequest\x12\x0b\n\x03min\x18\x01 \x01(\x03\x12\x0b\n\x03max\x18\x02 \x01(\x03\"\x1c\n\x0bPrimeNumber\x12\r\n\x05value\x18\x01 \x01(\x03\x32\xc6\x01\n\x0cPrimeService\x12\x34\n\x07IsPrime\x12\x13.prime.PrimeRequest\x1a\x14.prime.PrimeResponse\x12\x41\n\nFirstPrime\x12\x18.prime.FirstPrimeRequest\x1a\x19.prime.FirstPrimeResponse\x12=\n\rIntervalPrime\x12\x16.prime.IntervalRequest\x1a\x12.prime.PrimeNumber0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRIMEREQUEST']._serialized_start=22
  _globals['_PRIMEREQUEST']._serialized_end=52
  _globals['_PRIMERESPONSE']._serialized_start=54
  _globals['_PRIMERESPONSE']._serialized_end=104
  _globals['_FIRSTPRIMEREQUEST']._serialized_start=106
  _globals['_FIRSTPRIMEREQUEST']._serialized_end=136
  _globals['_FIRSTPRIMERESPONSE']._serialized_start=138
  _globals['_FIRSTPRIMERESPONSE']._serialized_end=174
  _globals['_INTERVALREQUEST']._serialized_start=176
  _globals['_INTERVALREQUEST']._serialized_end=219
  _globals['_PRIMENUMBER']._serialized_start=221
  _globals['_PRIMENUMBER']._serialized_end=249
  _globals['_PRIMESERVICE']._serialized_start=252
  _globals['_PRIMESERVICE']._serialized_end=450
# @@protoc_insertion_point(module_scope)
