# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import prime_pb2 as prime__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in prime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PrimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IsPrime = channel.unary_unary(
                '/prime.PrimeService/IsPrime',
                request_serializer=prime__pb2.PrimeRequest.SerializeToString,
                response_deserializer=prime__pb2.PrimeResponse.FromString,
                _registered_method=True)
        self.FirstPrime = channel.unary_unary(
                '/prime.PrimeService/FirstPrime',
                request_serializer=prime__pb2.FirstPrimeRequest.SerializeToString,
                response_deserializer=prime__pb2.FirstPrimeResponse.FromString,
                _registered_method=True)
        self.IntervalPrime = channel.unary_stream(
                '/prime.PrimeService/IntervalPrime',
                request_serializer=prime__pb2.IntervalRequest.SerializeToString,
                response_deserializer=prime__pb2.PrimeNumber.FromString,
                _registered_method=True)


class PrimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IsPrime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FirstPrime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IntervalPrime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IsPrime': grpc.unary_unary_rpc_method_handler(
                    servicer.IsPrime,
                    request_deserializer=prime__pb2.PrimeRequest.FromString,
                    response_serializer=prime__pb2.PrimeResponse.SerializeToString,
            ),
            'FirstPrime': grpc.unary_unary_rpc_method_handler(
                    servicer.FirstPrime,
                    request_deserializer=prime__pb2.FirstPrimeRequest.FromString,
                    response_serializer=prime__pb2.FirstPrimeResponse.SerializeToString,
            ),
            'IntervalPrime': grpc.unary_stream_rpc_method_handler(
                    servicer.IntervalPrime,
                    request_deserializer=prime__pb2.IntervalRequest.FromString,
                    response_serializer=prime__pb2.PrimeNumber.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'prime.PrimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('prime.PrimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IsPrime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prime.PrimeService/IsPrime',
            prime__pb2.PrimeRequest.SerializeToString,
            prime__pb2.PrimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FirstPrime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prime.PrimeService/FirstPrime',
            prime__pb2.FirstPrimeRequest.SerializeToString,
            prime__pb2.FirstPrimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IntervalPrime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/prime.PrimeService/IntervalPrime',
            prime__pb2.IntervalRequest.SerializeToString,
            prime__pb2.PrimeNumber.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
