// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prime.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_prime_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_prime_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_prime_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_prime_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_prime_2eproto;
namespace prime {
class FirstPrimeRequest;
struct FirstPrimeRequestDefaultTypeInternal;
extern FirstPrimeRequestDefaultTypeInternal _FirstPrimeRequest_default_instance_;
class FirstPrimeResponse;
struct FirstPrimeResponseDefaultTypeInternal;
extern FirstPrimeResponseDefaultTypeInternal _FirstPrimeResponse_default_instance_;
class IntervalRequest;
struct IntervalRequestDefaultTypeInternal;
extern IntervalRequestDefaultTypeInternal _IntervalRequest_default_instance_;
class PrimeNumber;
struct PrimeNumberDefaultTypeInternal;
extern PrimeNumberDefaultTypeInternal _PrimeNumber_default_instance_;
class PrimeRequest;
struct PrimeRequestDefaultTypeInternal;
extern PrimeRequestDefaultTypeInternal _PrimeRequest_default_instance_;
class PrimeResponse;
struct PrimeResponseDefaultTypeInternal;
extern PrimeResponseDefaultTypeInternal _PrimeResponse_default_instance_;
}  // namespace prime
PROTOBUF_NAMESPACE_OPEN
template<> ::prime::FirstPrimeRequest* Arena::CreateMaybeMessage<::prime::FirstPrimeRequest>(Arena*);
template<> ::prime::FirstPrimeResponse* Arena::CreateMaybeMessage<::prime::FirstPrimeResponse>(Arena*);
template<> ::prime::IntervalRequest* Arena::CreateMaybeMessage<::prime::IntervalRequest>(Arena*);
template<> ::prime::PrimeNumber* Arena::CreateMaybeMessage<::prime::PrimeNumber>(Arena*);
template<> ::prime::PrimeRequest* Arena::CreateMaybeMessage<::prime::PrimeRequest>(Arena*);
template<> ::prime::PrimeResponse* Arena::CreateMaybeMessage<::prime::PrimeResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace prime {

// ===================================================================

class PrimeRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:prime.PrimeRequest) */ {
 public:
  inline PrimeRequest() : PrimeRequest(nullptr) {}
  ~PrimeRequest() override;
  explicit PROTOBUF_CONSTEXPR PrimeRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PrimeRequest(const PrimeRequest& from);
  PrimeRequest(PrimeRequest&& from) noexcept
    : PrimeRequest() {
    *this = ::std::move(from);
  }

  inline PrimeRequest& operator=(const PrimeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PrimeRequest& operator=(PrimeRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PrimeRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const PrimeRequest* internal_default_instance() {
    return reinterpret_cast<const PrimeRequest*>(
               &_PrimeRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PrimeRequest& a, PrimeRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(PrimeRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PrimeRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PrimeRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PrimeRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PrimeRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PrimeRequest& from) {
    PrimeRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PrimeRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "prime.PrimeRequest";
  }
  protected:
  explicit PrimeRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNumberFieldNumber = 1,
  };
  // int64 number = 1;
  void clear_number();
  int64_t number() const;
  void set_number(int64_t value);
  private:
  int64_t _internal_number() const;
  void _internal_set_number(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:prime.PrimeRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t number_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_prime_2eproto;
};
// -------------------------------------------------------------------

class PrimeResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:prime.PrimeResponse) */ {
 public:
  inline PrimeResponse() : PrimeResponse(nullptr) {}
  ~PrimeResponse() override;
  explicit PROTOBUF_CONSTEXPR PrimeResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PrimeResponse(const PrimeResponse& from);
  PrimeResponse(PrimeResponse&& from) noexcept
    : PrimeResponse() {
    *this = ::std::move(from);
  }

  inline PrimeResponse& operator=(const PrimeResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PrimeResponse& operator=(PrimeResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PrimeResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const PrimeResponse* internal_default_instance() {
    return reinterpret_cast<const PrimeResponse*>(
               &_PrimeResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PrimeResponse& a, PrimeResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(PrimeResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PrimeResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PrimeResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PrimeResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PrimeResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PrimeResponse& from) {
    PrimeResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PrimeResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "prime.PrimeResponse";
  }
  protected:
  explicit PrimeResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFactorsFieldNumber = 2,
    kIsPrimeFieldNumber = 1,
  };
  // repeated int64 factors = 2;
  int factors_size() const;
  private:
  int _internal_factors_size() const;
  public:
  void clear_factors();
  private:
  int64_t _internal_factors(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
      _internal_factors() const;
  void _internal_add_factors(int64_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
      _internal_mutable_factors();
  public:
  int64_t factors(int index) const;
  void set_factors(int index, int64_t value);
  void add_factors(int64_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
      factors() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
      mutable_factors();

  // bool is_prime = 1;
  void clear_is_prime();
  bool is_prime() const;
  void set_is_prime(bool value);
  private:
  bool _internal_is_prime() const;
  void _internal_set_is_prime(bool value);
  public:

  // @@protoc_insertion_point(class_scope:prime.PrimeResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t > factors_;
    mutable std::atomic<int> _factors_cached_byte_size_;
    bool is_prime_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_prime_2eproto;
};
// -------------------------------------------------------------------

class FirstPrimeRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:prime.FirstPrimeRequest) */ {
 public:
  inline FirstPrimeRequest() : FirstPrimeRequest(nullptr) {}
  ~FirstPrimeRequest() override;
  explicit PROTOBUF_CONSTEXPR FirstPrimeRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FirstPrimeRequest(const FirstPrimeRequest& from);
  FirstPrimeRequest(FirstPrimeRequest&& from) noexcept
    : FirstPrimeRequest() {
    *this = ::std::move(from);
  }

  inline FirstPrimeRequest& operator=(const FirstPrimeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline FirstPrimeRequest& operator=(FirstPrimeRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FirstPrimeRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const FirstPrimeRequest* internal_default_instance() {
    return reinterpret_cast<const FirstPrimeRequest*>(
               &_FirstPrimeRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(FirstPrimeRequest& a, FirstPrimeRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(FirstPrimeRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FirstPrimeRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FirstPrimeRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FirstPrimeRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FirstPrimeRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FirstPrimeRequest& from) {
    FirstPrimeRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FirstPrimeRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "prime.FirstPrimeRequest";
  }
  protected:
  explicit FirstPrimeRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNFieldNumber = 1,
  };
  // int64 n = 1;
  void clear_n();
  int64_t n() const;
  void set_n(int64_t value);
  private:
  int64_t _internal_n() const;
  void _internal_set_n(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:prime.FirstPrimeRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t n_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_prime_2eproto;
};
// -------------------------------------------------------------------

class FirstPrimeResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:prime.FirstPrimeResponse) */ {
 public:
  inline FirstPrimeResponse() : FirstPrimeResponse(nullptr) {}
  ~FirstPrimeResponse() override;
  explicit PROTOBUF_CONSTEXPR FirstPrimeResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FirstPrimeResponse(const FirstPrimeResponse& from);
  FirstPrimeResponse(FirstPrimeResponse&& from) noexcept
    : FirstPrimeResponse() {
    *this = ::std::move(from);
  }

  inline FirstPrimeResponse& operator=(const FirstPrimeResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline FirstPrimeResponse& operator=(FirstPrimeResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FirstPrimeResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const FirstPrimeResponse* internal_default_instance() {
    return reinterpret_cast<const FirstPrimeResponse*>(
               &_FirstPrimeResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(FirstPrimeResponse& a, FirstPrimeResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(FirstPrimeResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FirstPrimeResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FirstPrimeResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FirstPrimeResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FirstPrimeResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FirstPrimeResponse& from) {
    FirstPrimeResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FirstPrimeResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "prime.FirstPrimeResponse";
  }
  protected:
  explicit FirstPrimeResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPrimesFieldNumber = 1,
  };
  // repeated int64 primes = 1;
  int primes_size() const;
  private:
  int _internal_primes_size() const;
  public:
  void clear_primes();
  private:
  int64_t _internal_primes(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
      _internal_primes() const;
  void _internal_add_primes(int64_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
      _internal_mutable_primes();
  public:
  int64_t primes(int index) const;
  void set_primes(int index, int64_t value);
  void add_primes(int64_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
      primes() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
      mutable_primes();

  // @@protoc_insertion_point(class_scope:prime.FirstPrimeResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t > primes_;
    mutable std::atomic<int> _primes_cached_byte_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_prime_2eproto;
};
// -------------------------------------------------------------------

class IntervalRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:prime.IntervalRequest) */ {
 public:
  inline IntervalRequest() : IntervalRequest(nullptr) {}
  ~IntervalRequest() override;
  explicit PROTOBUF_CONSTEXPR IntervalRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IntervalRequest(const IntervalRequest& from);
  IntervalRequest(IntervalRequest&& from) noexcept
    : IntervalRequest() {
    *this = ::std::move(from);
  }

  inline IntervalRequest& operator=(const IntervalRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline IntervalRequest& operator=(IntervalRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IntervalRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const IntervalRequest* internal_default_instance() {
    return reinterpret_cast<const IntervalRequest*>(
               &_IntervalRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(IntervalRequest& a, IntervalRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(IntervalRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IntervalRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IntervalRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IntervalRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const IntervalRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const IntervalRequest& from) {
    IntervalRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IntervalRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "prime.IntervalRequest";
  }
  protected:
  explicit IntervalRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMinFieldNumber = 1,
    kMaxFieldNumber = 2,
  };
  // int64 min = 1;
  void clear_min();
  int64_t min() const;
  void set_min(int64_t value);
  private:
  int64_t _internal_min() const;
  void _internal_set_min(int64_t value);
  public:

  // int64 max = 2;
  void clear_max();
  int64_t max() const;
  void set_max(int64_t value);
  private:
  int64_t _internal_max() const;
  void _internal_set_max(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:prime.IntervalRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t min_;
    int64_t max_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_prime_2eproto;
};
// -------------------------------------------------------------------

class PrimeNumber final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:prime.PrimeNumber) */ {
 public:
  inline PrimeNumber() : PrimeNumber(nullptr) {}
  ~PrimeNumber() override;
  explicit PROTOBUF_CONSTEXPR PrimeNumber(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PrimeNumber(const PrimeNumber& from);
  PrimeNumber(PrimeNumber&& from) noexcept
    : PrimeNumber() {
    *this = ::std::move(from);
  }

  inline PrimeNumber& operator=(const PrimeNumber& from) {
    CopyFrom(from);
    return *this;
  }
  inline PrimeNumber& operator=(PrimeNumber&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PrimeNumber& default_instance() {
    return *internal_default_instance();
  }
  static inline const PrimeNumber* internal_default_instance() {
    return reinterpret_cast<const PrimeNumber*>(
               &_PrimeNumber_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(PrimeNumber& a, PrimeNumber& b) {
    a.Swap(&b);
  }
  inline void Swap(PrimeNumber* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PrimeNumber* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PrimeNumber* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PrimeNumber>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PrimeNumber& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PrimeNumber& from) {
    PrimeNumber::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PrimeNumber* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "prime.PrimeNumber";
  }
  protected:
  explicit PrimeNumber(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
  };
  // int64 value = 1;
  void clear_value();
  int64_t value() const;
  void set_value(int64_t value);
  private:
  int64_t _internal_value() const;
  void _internal_set_value(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:prime.PrimeNumber)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t value_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_prime_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PrimeRequest

// int64 number = 1;
inline void PrimeRequest::clear_number() {
  _impl_.number_ = int64_t{0};
}
inline int64_t PrimeRequest::_internal_number() const {
  return _impl_.number_;
}
inline int64_t PrimeRequest::number() const {
  // @@protoc_insertion_point(field_get:prime.PrimeRequest.number)
  return _internal_number();
}
inline void PrimeRequest::_internal_set_number(int64_t value) {
  
  _impl_.number_ = value;
}
inline void PrimeRequest::set_number(int64_t value) {
  _internal_set_number(value);
  // @@protoc_insertion_point(field_set:prime.PrimeRequest.number)
}

// -------------------------------------------------------------------

// PrimeResponse

// bool is_prime = 1;
inline void PrimeResponse::clear_is_prime() {
  _impl_.is_prime_ = false;
}
inline bool PrimeResponse::_internal_is_prime() const {
  return _impl_.is_prime_;
}
inline bool PrimeResponse::is_prime() const {
  // @@protoc_insertion_point(field_get:prime.PrimeResponse.is_prime)
  return _internal_is_prime();
}
inline void PrimeResponse::_internal_set_is_prime(bool value) {
  
  _impl_.is_prime_ = value;
}
inline void PrimeResponse::set_is_prime(bool value) {
  _internal_set_is_prime(value);
  // @@protoc_insertion_point(field_set:prime.PrimeResponse.is_prime)
}

// repeated int64 factors = 2;
inline int PrimeResponse::_internal_factors_size() const {
  return _impl_.factors_.size();
}
inline int PrimeResponse::factors_size() const {
  return _internal_factors_size();
}
inline void PrimeResponse::clear_factors() {
  _impl_.factors_.Clear();
}
inline int64_t PrimeResponse::_internal_factors(int index) const {
  return _impl_.factors_.Get(index);
}
inline int64_t PrimeResponse::factors(int index) const {
  // @@protoc_insertion_point(field_get:prime.PrimeResponse.factors)
  return _internal_factors(index);
}
inline void PrimeResponse::set_factors(int index, int64_t value) {
  _impl_.factors_.Set(index, value);
  // @@protoc_insertion_point(field_set:prime.PrimeResponse.factors)
}
inline void PrimeResponse::_internal_add_factors(int64_t value) {
  _impl_.factors_.Add(value);
}
inline void PrimeResponse::add_factors(int64_t value) {
  _internal_add_factors(value);
  // @@protoc_insertion_point(field_add:prime.PrimeResponse.factors)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
PrimeResponse::_internal_factors() const {
  return _impl_.factors_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
PrimeResponse::factors() const {
  // @@protoc_insertion_point(field_list:prime.PrimeResponse.factors)
  return _internal_factors();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
PrimeResponse::_internal_mutable_factors() {
  return &_impl_.factors_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
PrimeResponse::mutable_factors() {
  // @@protoc_insertion_point(field_mutable_list:prime.PrimeResponse.factors)
  return _internal_mutable_factors();
}

// -------------------------------------------------------------------

// FirstPrimeRequest

// int64 n = 1;
inline void FirstPrimeRequest::clear_n() {
  _impl_.n_ = int64_t{0};
}
inline int64_t FirstPrimeRequest::_internal_n() const {
  return _impl_.n_;
}
inline int64_t FirstPrimeRequest::n() const {
  // @@protoc_insertion_point(field_get:prime.FirstPrimeRequest.n)
  return _internal_n();
}
inline void FirstPrimeRequest::_internal_set_n(int64_t value) {
  
  _impl_.n_ = value;
}
inline void FirstPrimeRequest::set_n(int64_t value) {
  _internal_set_n(value);
  // @@protoc_insertion_point(field_set:prime.FirstPrimeRequest.n)
}

// -------------------------------------------------------------------

// FirstPrimeResponse

// repeated int64 primes = 1;
inline int FirstPrimeResponse::_internal_primes_size() const {
  return _impl_.primes_.size();
}
inline int FirstPrimeResponse::primes_size() const {
  return _internal_primes_size();
}
inline void FirstPrimeResponse::clear_primes() {
  _impl_.primes_.Clear();
}
inline int64_t FirstPrimeResponse::_internal_primes(int index) const {
  return _impl_.primes_.Get(index);
}
inline int64_t FirstPrimeResponse::primes(int index) const {
  // @@protoc_insertion_point(field_get:prime.FirstPrimeResponse.primes)
  return _internal_primes(index);
}
inline void FirstPrimeResponse::set_primes(int index, int64_t value) {
  _impl_.primes_.Set(index, value);
  // @@protoc_insertion_point(field_set:prime.FirstPrimeResponse.primes)
}
inline void FirstPrimeResponse::_internal_add_primes(int64_t value) {
  _impl_.primes_.Add(value);
}
inline void FirstPrimeResponse::add_primes(int64_t value) {
  _internal_add_primes(value);
  // @@protoc_insertion_point(field_add:prime.FirstPrimeResponse.primes)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
FirstPrimeResponse::_internal_primes() const {
  return _impl_.primes_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
FirstPrimeResponse::primes() const {
  // @@protoc_insertion_point(field_list:prime.FirstPrimeResponse.primes)
  return _internal_primes();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
FirstPrimeResponse::_internal_mutable_primes() {
  return &_impl_.primes_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
FirstPrimeResponse::mutable_primes() {
  // @@protoc_insertion_point(field_mutable_list:prime.FirstPrimeResponse.primes)
  return _internal_mutable_primes();
}

// -------------------------------------------------------------------

// IntervalRequest

// int64 min = 1;
inline void IntervalRequest::clear_min() {
  _impl_.min_ = int64_t{0};
}
inline int64_t IntervalRequest::_internal_min() const {
  return _impl_.min_;
}
inline int64_t IntervalRequest::min() const {
  // @@protoc_insertion_point(field_get:prime.IntervalRequest.min)
  return _internal_min();
}
inline void IntervalRequest::_internal_set_min(int64_t value) {
  
  _impl_.min_ = value;
}
inline void IntervalRequest::set_min(int64_t value) {
  _internal_set_min(value);
  // @@protoc_insertion_point(field_set:prime.IntervalRequest.min)
}

// int64 max = 2;
inline void IntervalRequest::clear_max() {
  _impl_.max_ = int64_t{0};
}
inline int64_t IntervalRequest::_internal_max() const {
  return _impl_.max_;
}
inline int64_t IntervalRequest::max() const {
  // @@protoc_insertion_point(field_get:prime.IntervalRequest.max)
  return _internal_max();
}
inline void IntervalRequest::_internal_set_max(int64_t value) {
  
  _impl_.max_ = value;
}
inline void IntervalRequest::set_max(int64_t value) {
  _internal_set_max(value);
  // @@protoc_insertion_point(field_set:prime.IntervalRequest.max)
}

// -------------------------------------------------------------------

// PrimeNumber

// int64 value = 1;
inline void PrimeNumber::clear_value() {
  _impl_.value_ = int64_t{0};
}
inline int64_t PrimeNumber::_internal_value() const {
  return _impl_.value_;
}
inline int64_t PrimeNumber::value() const {
  // @@protoc_insertion_point(field_get:prime.PrimeNumber.value)
  return _internal_value();
}
inline void PrimeNumber::_internal_set_value(int64_t value) {
  
  _impl_.value_ = value;
}
inline void PrimeNumber::set_value(int64_t value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:prime.PrimeNumber.value)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace prime

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_prime_2eproto
