// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: prime.proto
#ifndef GRPC_prime_2eproto__INCLUDED
#define GRPC_prime_2eproto__INCLUDED

#include "prime.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace prime {

class PrimeService final {
 public:
  static constexpr char const* service_full_name() {
    return "prime.PrimeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status IsPrime(::grpc::ClientContext* context, const ::prime::PrimeRequest& request, ::prime::PrimeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::prime::PrimeResponse>> AsyncIsPrime(::grpc::ClientContext* context, const ::prime::PrimeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::prime::PrimeResponse>>(AsyncIsPrimeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::prime::PrimeResponse>> PrepareAsyncIsPrime(::grpc::ClientContext* context, const ::prime::PrimeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::prime::PrimeResponse>>(PrepareAsyncIsPrimeRaw(context, request, cq));
    }
    virtual ::grpc::Status FirstPrime(::grpc::ClientContext* context, const ::prime::FirstPrimeRequest& request, ::prime::FirstPrimeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::prime::FirstPrimeResponse>> AsyncFirstPrime(::grpc::ClientContext* context, const ::prime::FirstPrimeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::prime::FirstPrimeResponse>>(AsyncFirstPrimeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::prime::FirstPrimeResponse>> PrepareAsyncFirstPrime(::grpc::ClientContext* context, const ::prime::FirstPrimeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::prime::FirstPrimeResponse>>(PrepareAsyncFirstPrimeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::prime::PrimeNumber>> IntervalPrime(::grpc::ClientContext* context, const ::prime::IntervalRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::prime::PrimeNumber>>(IntervalPrimeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::prime::PrimeNumber>> AsyncIntervalPrime(::grpc::ClientContext* context, const ::prime::IntervalRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::prime::PrimeNumber>>(AsyncIntervalPrimeRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::prime::PrimeNumber>> PrepareAsyncIntervalPrime(::grpc::ClientContext* context, const ::prime::IntervalRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::prime::PrimeNumber>>(PrepareAsyncIntervalPrimeRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void IsPrime(::grpc::ClientContext* context, const ::prime::PrimeRequest* request, ::prime::PrimeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void IsPrime(::grpc::ClientContext* context, const ::prime::PrimeRequest* request, ::prime::PrimeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void FirstPrime(::grpc::ClientContext* context, const ::prime::FirstPrimeRequest* request, ::prime::FirstPrimeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FirstPrime(::grpc::ClientContext* context, const ::prime::FirstPrimeRequest* request, ::prime::FirstPrimeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void IntervalPrime(::grpc::ClientContext* context, const ::prime::IntervalRequest* request, ::grpc::ClientReadReactor< ::prime::PrimeNumber>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::prime::PrimeResponse>* AsyncIsPrimeRaw(::grpc::ClientContext* context, const ::prime::PrimeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::prime::PrimeResponse>* PrepareAsyncIsPrimeRaw(::grpc::ClientContext* context, const ::prime::PrimeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::prime::FirstPrimeResponse>* AsyncFirstPrimeRaw(::grpc::ClientContext* context, const ::prime::FirstPrimeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::prime::FirstPrimeResponse>* PrepareAsyncFirstPrimeRaw(::grpc::ClientContext* context, const ::prime::FirstPrimeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::prime::PrimeNumber>* IntervalPrimeRaw(::grpc::ClientContext* context, const ::prime::IntervalRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::prime::PrimeNumber>* AsyncIntervalPrimeRaw(::grpc::ClientContext* context, const ::prime::IntervalRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::prime::PrimeNumber>* PrepareAsyncIntervalPrimeRaw(::grpc::ClientContext* context, const ::prime::IntervalRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status IsPrime(::grpc::ClientContext* context, const ::prime::PrimeRequest& request, ::prime::PrimeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::prime::PrimeResponse>> AsyncIsPrime(::grpc::ClientContext* context, const ::prime::PrimeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::prime::PrimeResponse>>(AsyncIsPrimeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::prime::PrimeResponse>> PrepareAsyncIsPrime(::grpc::ClientContext* context, const ::prime::PrimeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::prime::PrimeResponse>>(PrepareAsyncIsPrimeRaw(context, request, cq));
    }
    ::grpc::Status FirstPrime(::grpc::ClientContext* context, const ::prime::FirstPrimeRequest& request, ::prime::FirstPrimeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::prime::FirstPrimeResponse>> AsyncFirstPrime(::grpc::ClientContext* context, const ::prime::FirstPrimeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::prime::FirstPrimeResponse>>(AsyncFirstPrimeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::prime::FirstPrimeResponse>> PrepareAsyncFirstPrime(::grpc::ClientContext* context, const ::prime::FirstPrimeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::prime::FirstPrimeResponse>>(PrepareAsyncFirstPrimeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::prime::PrimeNumber>> IntervalPrime(::grpc::ClientContext* context, const ::prime::IntervalRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::prime::PrimeNumber>>(IntervalPrimeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::prime::PrimeNumber>> AsyncIntervalPrime(::grpc::ClientContext* context, const ::prime::IntervalRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::prime::PrimeNumber>>(AsyncIntervalPrimeRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::prime::PrimeNumber>> PrepareAsyncIntervalPrime(::grpc::ClientContext* context, const ::prime::IntervalRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::prime::PrimeNumber>>(PrepareAsyncIntervalPrimeRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void IsPrime(::grpc::ClientContext* context, const ::prime::PrimeRequest* request, ::prime::PrimeResponse* response, std::function<void(::grpc::Status)>) override;
      void IsPrime(::grpc::ClientContext* context, const ::prime::PrimeRequest* request, ::prime::PrimeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void FirstPrime(::grpc::ClientContext* context, const ::prime::FirstPrimeRequest* request, ::prime::FirstPrimeResponse* response, std::function<void(::grpc::Status)>) override;
      void FirstPrime(::grpc::ClientContext* context, const ::prime::FirstPrimeRequest* request, ::prime::FirstPrimeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void IntervalPrime(::grpc::ClientContext* context, const ::prime::IntervalRequest* request, ::grpc::ClientReadReactor< ::prime::PrimeNumber>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::prime::PrimeResponse>* AsyncIsPrimeRaw(::grpc::ClientContext* context, const ::prime::PrimeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::prime::PrimeResponse>* PrepareAsyncIsPrimeRaw(::grpc::ClientContext* context, const ::prime::PrimeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::prime::FirstPrimeResponse>* AsyncFirstPrimeRaw(::grpc::ClientContext* context, const ::prime::FirstPrimeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::prime::FirstPrimeResponse>* PrepareAsyncFirstPrimeRaw(::grpc::ClientContext* context, const ::prime::FirstPrimeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::prime::PrimeNumber>* IntervalPrimeRaw(::grpc::ClientContext* context, const ::prime::IntervalRequest& request) override;
    ::grpc::ClientAsyncReader< ::prime::PrimeNumber>* AsyncIntervalPrimeRaw(::grpc::ClientContext* context, const ::prime::IntervalRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::prime::PrimeNumber>* PrepareAsyncIntervalPrimeRaw(::grpc::ClientContext* context, const ::prime::IntervalRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_IsPrime_;
    const ::grpc::internal::RpcMethod rpcmethod_FirstPrime_;
    const ::grpc::internal::RpcMethod rpcmethod_IntervalPrime_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status IsPrime(::grpc::ServerContext* context, const ::prime::PrimeRequest* request, ::prime::PrimeResponse* response);
    virtual ::grpc::Status FirstPrime(::grpc::ServerContext* context, const ::prime::FirstPrimeRequest* request, ::prime::FirstPrimeResponse* response);
    virtual ::grpc::Status IntervalPrime(::grpc::ServerContext* context, const ::prime::IntervalRequest* request, ::grpc::ServerWriter< ::prime::PrimeNumber>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_IsPrime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_IsPrime() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_IsPrime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsPrime(::grpc::ServerContext* /*context*/, const ::prime::PrimeRequest* /*request*/, ::prime::PrimeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIsPrime(::grpc::ServerContext* context, ::prime::PrimeRequest* request, ::grpc::ServerAsyncResponseWriter< ::prime::PrimeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_FirstPrime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FirstPrime() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_FirstPrime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FirstPrime(::grpc::ServerContext* /*context*/, const ::prime::FirstPrimeRequest* /*request*/, ::prime::FirstPrimeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFirstPrime(::grpc::ServerContext* context, ::prime::FirstPrimeRequest* request, ::grpc::ServerAsyncResponseWriter< ::prime::FirstPrimeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_IntervalPrime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_IntervalPrime() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_IntervalPrime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IntervalPrime(::grpc::ServerContext* /*context*/, const ::prime::IntervalRequest* /*request*/, ::grpc::ServerWriter< ::prime::PrimeNumber>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIntervalPrime(::grpc::ServerContext* context, ::prime::IntervalRequest* request, ::grpc::ServerAsyncWriter< ::prime::PrimeNumber>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_IsPrime<WithAsyncMethod_FirstPrime<WithAsyncMethod_IntervalPrime<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_IsPrime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_IsPrime() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::prime::PrimeRequest, ::prime::PrimeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::prime::PrimeRequest* request, ::prime::PrimeResponse* response) { return this->IsPrime(context, request, response); }));}
    void SetMessageAllocatorFor_IsPrime(
        ::grpc::MessageAllocator< ::prime::PrimeRequest, ::prime::PrimeResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::prime::PrimeRequest, ::prime::PrimeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_IsPrime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsPrime(::grpc::ServerContext* /*context*/, const ::prime::PrimeRequest* /*request*/, ::prime::PrimeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* IsPrime(
      ::grpc::CallbackServerContext* /*context*/, const ::prime::PrimeRequest* /*request*/, ::prime::PrimeResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_FirstPrime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FirstPrime() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::prime::FirstPrimeRequest, ::prime::FirstPrimeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::prime::FirstPrimeRequest* request, ::prime::FirstPrimeResponse* response) { return this->FirstPrime(context, request, response); }));}
    void SetMessageAllocatorFor_FirstPrime(
        ::grpc::MessageAllocator< ::prime::FirstPrimeRequest, ::prime::FirstPrimeResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::prime::FirstPrimeRequest, ::prime::FirstPrimeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FirstPrime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FirstPrime(::grpc::ServerContext* /*context*/, const ::prime::FirstPrimeRequest* /*request*/, ::prime::FirstPrimeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FirstPrime(
      ::grpc::CallbackServerContext* /*context*/, const ::prime::FirstPrimeRequest* /*request*/, ::prime::FirstPrimeResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_IntervalPrime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_IntervalPrime() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackServerStreamingHandler< ::prime::IntervalRequest, ::prime::PrimeNumber>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::prime::IntervalRequest* request) { return this->IntervalPrime(context, request); }));
    }
    ~WithCallbackMethod_IntervalPrime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IntervalPrime(::grpc::ServerContext* /*context*/, const ::prime::IntervalRequest* /*request*/, ::grpc::ServerWriter< ::prime::PrimeNumber>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::prime::PrimeNumber>* IntervalPrime(
      ::grpc::CallbackServerContext* /*context*/, const ::prime::IntervalRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_IsPrime<WithCallbackMethod_FirstPrime<WithCallbackMethod_IntervalPrime<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_IsPrime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_IsPrime() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_IsPrime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsPrime(::grpc::ServerContext* /*context*/, const ::prime::PrimeRequest* /*request*/, ::prime::PrimeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_FirstPrime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FirstPrime() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_FirstPrime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FirstPrime(::grpc::ServerContext* /*context*/, const ::prime::FirstPrimeRequest* /*request*/, ::prime::FirstPrimeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_IntervalPrime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_IntervalPrime() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_IntervalPrime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IntervalPrime(::grpc::ServerContext* /*context*/, const ::prime::IntervalRequest* /*request*/, ::grpc::ServerWriter< ::prime::PrimeNumber>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_IsPrime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_IsPrime() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_IsPrime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsPrime(::grpc::ServerContext* /*context*/, const ::prime::PrimeRequest* /*request*/, ::prime::PrimeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIsPrime(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_FirstPrime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FirstPrime() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_FirstPrime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FirstPrime(::grpc::ServerContext* /*context*/, const ::prime::FirstPrimeRequest* /*request*/, ::prime::FirstPrimeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFirstPrime(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_IntervalPrime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_IntervalPrime() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_IntervalPrime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IntervalPrime(::grpc::ServerContext* /*context*/, const ::prime::IntervalRequest* /*request*/, ::grpc::ServerWriter< ::prime::PrimeNumber>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIntervalPrime(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_IsPrime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_IsPrime() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->IsPrime(context, request, response); }));
    }
    ~WithRawCallbackMethod_IsPrime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IsPrime(::grpc::ServerContext* /*context*/, const ::prime::PrimeRequest* /*request*/, ::prime::PrimeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* IsPrime(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FirstPrime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FirstPrime() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FirstPrime(context, request, response); }));
    }
    ~WithRawCallbackMethod_FirstPrime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FirstPrime(::grpc::ServerContext* /*context*/, const ::prime::FirstPrimeRequest* /*request*/, ::prime::FirstPrimeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FirstPrime(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_IntervalPrime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_IntervalPrime() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->IntervalPrime(context, request); }));
    }
    ~WithRawCallbackMethod_IntervalPrime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IntervalPrime(::grpc::ServerContext* /*context*/, const ::prime::IntervalRequest* /*request*/, ::grpc::ServerWriter< ::prime::PrimeNumber>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* IntervalPrime(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_IsPrime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_IsPrime() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::prime::PrimeRequest, ::prime::PrimeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::prime::PrimeRequest, ::prime::PrimeResponse>* streamer) {
                       return this->StreamedIsPrime(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_IsPrime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status IsPrime(::grpc::ServerContext* /*context*/, const ::prime::PrimeRequest* /*request*/, ::prime::PrimeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedIsPrime(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::prime::PrimeRequest,::prime::PrimeResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FirstPrime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FirstPrime() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::prime::FirstPrimeRequest, ::prime::FirstPrimeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::prime::FirstPrimeRequest, ::prime::FirstPrimeResponse>* streamer) {
                       return this->StreamedFirstPrime(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FirstPrime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FirstPrime(::grpc::ServerContext* /*context*/, const ::prime::FirstPrimeRequest* /*request*/, ::prime::FirstPrimeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFirstPrime(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::prime::FirstPrimeRequest,::prime::FirstPrimeResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_IsPrime<WithStreamedUnaryMethod_FirstPrime<Service > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_IntervalPrime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_IntervalPrime() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::prime::IntervalRequest, ::prime::PrimeNumber>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::prime::IntervalRequest, ::prime::PrimeNumber>* streamer) {
                       return this->StreamedIntervalPrime(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_IntervalPrime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status IntervalPrime(::grpc::ServerContext* /*context*/, const ::prime::IntervalRequest* /*request*/, ::grpc::ServerWriter< ::prime::PrimeNumber>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedIntervalPrime(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::prime::IntervalRequest,::prime::PrimeNumber>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_IntervalPrime<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_IsPrime<WithStreamedUnaryMethod_FirstPrime<WithSplitStreamingMethod_IntervalPrime<Service > > > StreamedService;
};

}  // namespace prime


#endif  // GRPC_prime_2eproto__INCLUDED
