// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prime.proto

#include "prime.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace prime {
PROTOBUF_CONSTEXPR PrimeRequest::PrimeRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.number_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PrimeRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PrimeRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PrimeRequestDefaultTypeInternal() {}
  union {
    PrimeRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PrimeRequestDefaultTypeInternal _PrimeRequest_default_instance_;
PROTOBUF_CONSTEXPR PrimeResponse::PrimeResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.factors_)*/{}
  , /*decltype(_impl_._factors_cached_byte_size_)*/{0}
  , /*decltype(_impl_.is_prime_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PrimeResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PrimeResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PrimeResponseDefaultTypeInternal() {}
  union {
    PrimeResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PrimeResponseDefaultTypeInternal _PrimeResponse_default_instance_;
PROTOBUF_CONSTEXPR FirstPrimeRequest::FirstPrimeRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.n_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FirstPrimeRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FirstPrimeRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FirstPrimeRequestDefaultTypeInternal() {}
  union {
    FirstPrimeRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FirstPrimeRequestDefaultTypeInternal _FirstPrimeRequest_default_instance_;
PROTOBUF_CONSTEXPR FirstPrimeResponse::FirstPrimeResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.primes_)*/{}
  , /*decltype(_impl_._primes_cached_byte_size_)*/{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FirstPrimeResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FirstPrimeResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FirstPrimeResponseDefaultTypeInternal() {}
  union {
    FirstPrimeResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FirstPrimeResponseDefaultTypeInternal _FirstPrimeResponse_default_instance_;
PROTOBUF_CONSTEXPR IntervalRequest::IntervalRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.min_)*/int64_t{0}
  , /*decltype(_impl_.max_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct IntervalRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IntervalRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~IntervalRequestDefaultTypeInternal() {}
  union {
    IntervalRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IntervalRequestDefaultTypeInternal _IntervalRequest_default_instance_;
PROTOBUF_CONSTEXPR PrimeNumber::PrimeNumber(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.value_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PrimeNumberDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PrimeNumberDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PrimeNumberDefaultTypeInternal() {}
  union {
    PrimeNumber _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PrimeNumberDefaultTypeInternal _PrimeNumber_default_instance_;
}  // namespace prime
static ::_pb::Metadata file_level_metadata_prime_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_prime_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_prime_2eproto = nullptr;

const uint32_t TableStruct_prime_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::prime::PrimeRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::prime::PrimeRequest, _impl_.number_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::prime::PrimeResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::prime::PrimeResponse, _impl_.is_prime_),
  PROTOBUF_FIELD_OFFSET(::prime::PrimeResponse, _impl_.factors_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::prime::FirstPrimeRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::prime::FirstPrimeRequest, _impl_.n_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::prime::FirstPrimeResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::prime::FirstPrimeResponse, _impl_.primes_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::prime::IntervalRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::prime::IntervalRequest, _impl_.min_),
  PROTOBUF_FIELD_OFFSET(::prime::IntervalRequest, _impl_.max_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::prime::PrimeNumber, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::prime::PrimeNumber, _impl_.value_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::prime::PrimeRequest)},
  { 7, -1, -1, sizeof(::prime::PrimeResponse)},
  { 15, -1, -1, sizeof(::prime::FirstPrimeRequest)},
  { 22, -1, -1, sizeof(::prime::FirstPrimeResponse)},
  { 29, -1, -1, sizeof(::prime::IntervalRequest)},
  { 37, -1, -1, sizeof(::prime::PrimeNumber)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::prime::_PrimeRequest_default_instance_._instance,
  &::prime::_PrimeResponse_default_instance_._instance,
  &::prime::_FirstPrimeRequest_default_instance_._instance,
  &::prime::_FirstPrimeResponse_default_instance_._instance,
  &::prime::_IntervalRequest_default_instance_._instance,
  &::prime::_PrimeNumber_default_instance_._instance,
};

const char descriptor_table_protodef_prime_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\013prime.proto\022\005prime\"\036\n\014PrimeRequest\022\016\n\006"
  "number\030\001 \001(\003\"2\n\rPrimeResponse\022\020\n\010is_prim"
  "e\030\001 \001(\010\022\017\n\007factors\030\002 \003(\003\"\036\n\021FirstPrimeRe"
  "quest\022\t\n\001n\030\001 \001(\003\"$\n\022FirstPrimeResponse\022\016"
  "\n\006primes\030\001 \003(\003\"+\n\017IntervalRequest\022\013\n\003min"
  "\030\001 \001(\003\022\013\n\003max\030\002 \001(\003\"\034\n\013PrimeNumber\022\r\n\005va"
  "lue\030\001 \001(\0032\306\001\n\014PrimeService\0224\n\007IsPrime\022\023."
  "prime.PrimeRequest\032\024.prime.PrimeResponse"
  "\022A\n\nFirstPrime\022\030.prime.FirstPrimeRequest"
  "\032\031.prime.FirstPrimeResponse\022=\n\rIntervalP"
  "rime\022\026.prime.IntervalRequest\032\022.prime.Pri"
  "meNumber0\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_prime_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_prime_2eproto = {
    false, false, 458, descriptor_table_protodef_prime_2eproto,
    "prime.proto",
    &descriptor_table_prime_2eproto_once, nullptr, 0, 6,
    schemas, file_default_instances, TableStruct_prime_2eproto::offsets,
    file_level_metadata_prime_2eproto, file_level_enum_descriptors_prime_2eproto,
    file_level_service_descriptors_prime_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_prime_2eproto_getter() {
  return &descriptor_table_prime_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_prime_2eproto(&descriptor_table_prime_2eproto);
namespace prime {

// ===================================================================

class PrimeRequest::_Internal {
 public:
};

PrimeRequest::PrimeRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:prime.PrimeRequest)
}
PrimeRequest::PrimeRequest(const PrimeRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PrimeRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.number_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.number_ = from._impl_.number_;
  // @@protoc_insertion_point(copy_constructor:prime.PrimeRequest)
}

inline void PrimeRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.number_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PrimeRequest::~PrimeRequest() {
  // @@protoc_insertion_point(destructor:prime.PrimeRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PrimeRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PrimeRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PrimeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:prime.PrimeRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.number_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PrimeRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 number = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.number_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PrimeRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:prime.PrimeRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 number = 1;
  if (this->_internal_number() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_number(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:prime.PrimeRequest)
  return target;
}

size_t PrimeRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:prime.PrimeRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 number = 1;
  if (this->_internal_number() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_number());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PrimeRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PrimeRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PrimeRequest::GetClassData() const { return &_class_data_; }


void PrimeRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PrimeRequest*>(&to_msg);
  auto& from = static_cast<const PrimeRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:prime.PrimeRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_number() != 0) {
    _this->_internal_set_number(from._internal_number());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PrimeRequest::CopyFrom(const PrimeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:prime.PrimeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PrimeRequest::IsInitialized() const {
  return true;
}

void PrimeRequest::InternalSwap(PrimeRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.number_, other->_impl_.number_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PrimeRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_prime_2eproto_getter, &descriptor_table_prime_2eproto_once,
      file_level_metadata_prime_2eproto[0]);
}

// ===================================================================

class PrimeResponse::_Internal {
 public:
};

PrimeResponse::PrimeResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:prime.PrimeResponse)
}
PrimeResponse::PrimeResponse(const PrimeResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PrimeResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.factors_){from._impl_.factors_}
    , /*decltype(_impl_._factors_cached_byte_size_)*/{0}
    , decltype(_impl_.is_prime_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.is_prime_ = from._impl_.is_prime_;
  // @@protoc_insertion_point(copy_constructor:prime.PrimeResponse)
}

inline void PrimeResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.factors_){arena}
    , /*decltype(_impl_._factors_cached_byte_size_)*/{0}
    , decltype(_impl_.is_prime_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PrimeResponse::~PrimeResponse() {
  // @@protoc_insertion_point(destructor:prime.PrimeResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PrimeResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.factors_.~RepeatedField();
}

void PrimeResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PrimeResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:prime.PrimeResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.factors_.Clear();
  _impl_.is_prime_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PrimeResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool is_prime = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.is_prime_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated int64 factors = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt64Parser(_internal_mutable_factors(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 16) {
          _internal_add_factors(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PrimeResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:prime.PrimeResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool is_prime = 1;
  if (this->_internal_is_prime() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_is_prime(), target);
  }

  // repeated int64 factors = 2;
  {
    int byte_size = _impl_._factors_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt64Packed(
          2, _internal_factors(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:prime.PrimeResponse)
  return target;
}

size_t PrimeResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:prime.PrimeResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int64 factors = 2;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int64Size(this->_impl_.factors_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._factors_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // bool is_prime = 1;
  if (this->_internal_is_prime() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PrimeResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PrimeResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PrimeResponse::GetClassData() const { return &_class_data_; }


void PrimeResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PrimeResponse*>(&to_msg);
  auto& from = static_cast<const PrimeResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:prime.PrimeResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.factors_.MergeFrom(from._impl_.factors_);
  if (from._internal_is_prime() != 0) {
    _this->_internal_set_is_prime(from._internal_is_prime());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PrimeResponse::CopyFrom(const PrimeResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:prime.PrimeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PrimeResponse::IsInitialized() const {
  return true;
}

void PrimeResponse::InternalSwap(PrimeResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.factors_.InternalSwap(&other->_impl_.factors_);
  swap(_impl_.is_prime_, other->_impl_.is_prime_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PrimeResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_prime_2eproto_getter, &descriptor_table_prime_2eproto_once,
      file_level_metadata_prime_2eproto[1]);
}

// ===================================================================

class FirstPrimeRequest::_Internal {
 public:
};

FirstPrimeRequest::FirstPrimeRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:prime.FirstPrimeRequest)
}
FirstPrimeRequest::FirstPrimeRequest(const FirstPrimeRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FirstPrimeRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.n_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.n_ = from._impl_.n_;
  // @@protoc_insertion_point(copy_constructor:prime.FirstPrimeRequest)
}

inline void FirstPrimeRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.n_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

FirstPrimeRequest::~FirstPrimeRequest() {
  // @@protoc_insertion_point(destructor:prime.FirstPrimeRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FirstPrimeRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void FirstPrimeRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FirstPrimeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:prime.FirstPrimeRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.n_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FirstPrimeRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 n = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.n_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FirstPrimeRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:prime.FirstPrimeRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 n = 1;
  if (this->_internal_n() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_n(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:prime.FirstPrimeRequest)
  return target;
}

size_t FirstPrimeRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:prime.FirstPrimeRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 n = 1;
  if (this->_internal_n() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_n());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FirstPrimeRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FirstPrimeRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FirstPrimeRequest::GetClassData() const { return &_class_data_; }


void FirstPrimeRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FirstPrimeRequest*>(&to_msg);
  auto& from = static_cast<const FirstPrimeRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:prime.FirstPrimeRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_n() != 0) {
    _this->_internal_set_n(from._internal_n());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FirstPrimeRequest::CopyFrom(const FirstPrimeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:prime.FirstPrimeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FirstPrimeRequest::IsInitialized() const {
  return true;
}

void FirstPrimeRequest::InternalSwap(FirstPrimeRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.n_, other->_impl_.n_);
}

::PROTOBUF_NAMESPACE_ID::Metadata FirstPrimeRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_prime_2eproto_getter, &descriptor_table_prime_2eproto_once,
      file_level_metadata_prime_2eproto[2]);
}

// ===================================================================

class FirstPrimeResponse::_Internal {
 public:
};

FirstPrimeResponse::FirstPrimeResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:prime.FirstPrimeResponse)
}
FirstPrimeResponse::FirstPrimeResponse(const FirstPrimeResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FirstPrimeResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.primes_){from._impl_.primes_}
    , /*decltype(_impl_._primes_cached_byte_size_)*/{0}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:prime.FirstPrimeResponse)
}

inline void FirstPrimeResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.primes_){arena}
    , /*decltype(_impl_._primes_cached_byte_size_)*/{0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

FirstPrimeResponse::~FirstPrimeResponse() {
  // @@protoc_insertion_point(destructor:prime.FirstPrimeResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FirstPrimeResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.primes_.~RepeatedField();
}

void FirstPrimeResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FirstPrimeResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:prime.FirstPrimeResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.primes_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FirstPrimeResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated int64 primes = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt64Parser(_internal_mutable_primes(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 8) {
          _internal_add_primes(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FirstPrimeResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:prime.FirstPrimeResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int64 primes = 1;
  {
    int byte_size = _impl_._primes_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt64Packed(
          1, _internal_primes(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:prime.FirstPrimeResponse)
  return target;
}

size_t FirstPrimeResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:prime.FirstPrimeResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int64 primes = 1;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int64Size(this->_impl_.primes_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._primes_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FirstPrimeResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FirstPrimeResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FirstPrimeResponse::GetClassData() const { return &_class_data_; }


void FirstPrimeResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FirstPrimeResponse*>(&to_msg);
  auto& from = static_cast<const FirstPrimeResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:prime.FirstPrimeResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.primes_.MergeFrom(from._impl_.primes_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FirstPrimeResponse::CopyFrom(const FirstPrimeResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:prime.FirstPrimeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FirstPrimeResponse::IsInitialized() const {
  return true;
}

void FirstPrimeResponse::InternalSwap(FirstPrimeResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.primes_.InternalSwap(&other->_impl_.primes_);
}

::PROTOBUF_NAMESPACE_ID::Metadata FirstPrimeResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_prime_2eproto_getter, &descriptor_table_prime_2eproto_once,
      file_level_metadata_prime_2eproto[3]);
}

// ===================================================================

class IntervalRequest::_Internal {
 public:
};

IntervalRequest::IntervalRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:prime.IntervalRequest)
}
IntervalRequest::IntervalRequest(const IntervalRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  IntervalRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.min_){}
    , decltype(_impl_.max_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.min_, &from._impl_.min_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.max_) -
    reinterpret_cast<char*>(&_impl_.min_)) + sizeof(_impl_.max_));
  // @@protoc_insertion_point(copy_constructor:prime.IntervalRequest)
}

inline void IntervalRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.min_){int64_t{0}}
    , decltype(_impl_.max_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

IntervalRequest::~IntervalRequest() {
  // @@protoc_insertion_point(destructor:prime.IntervalRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void IntervalRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void IntervalRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void IntervalRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:prime.IntervalRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.min_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.max_) -
      reinterpret_cast<char*>(&_impl_.min_)) + sizeof(_impl_.max_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* IntervalRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 min = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.min_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 max = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.max_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* IntervalRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:prime.IntervalRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 min = 1;
  if (this->_internal_min() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_min(), target);
  }

  // int64 max = 2;
  if (this->_internal_max() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_max(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:prime.IntervalRequest)
  return target;
}

size_t IntervalRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:prime.IntervalRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 min = 1;
  if (this->_internal_min() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_min());
  }

  // int64 max = 2;
  if (this->_internal_max() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_max());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData IntervalRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    IntervalRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*IntervalRequest::GetClassData() const { return &_class_data_; }


void IntervalRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<IntervalRequest*>(&to_msg);
  auto& from = static_cast<const IntervalRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:prime.IntervalRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_min() != 0) {
    _this->_internal_set_min(from._internal_min());
  }
  if (from._internal_max() != 0) {
    _this->_internal_set_max(from._internal_max());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void IntervalRequest::CopyFrom(const IntervalRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:prime.IntervalRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IntervalRequest::IsInitialized() const {
  return true;
}

void IntervalRequest::InternalSwap(IntervalRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(IntervalRequest, _impl_.max_)
      + sizeof(IntervalRequest::_impl_.max_)
      - PROTOBUF_FIELD_OFFSET(IntervalRequest, _impl_.min_)>(
          reinterpret_cast<char*>(&_impl_.min_),
          reinterpret_cast<char*>(&other->_impl_.min_));
}

::PROTOBUF_NAMESPACE_ID::Metadata IntervalRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_prime_2eproto_getter, &descriptor_table_prime_2eproto_once,
      file_level_metadata_prime_2eproto[4]);
}

// ===================================================================

class PrimeNumber::_Internal {
 public:
};

PrimeNumber::PrimeNumber(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:prime.PrimeNumber)
}
PrimeNumber::PrimeNumber(const PrimeNumber& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PrimeNumber* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.value_ = from._impl_.value_;
  // @@protoc_insertion_point(copy_constructor:prime.PrimeNumber)
}

inline void PrimeNumber::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.value_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PrimeNumber::~PrimeNumber() {
  // @@protoc_insertion_point(destructor:prime.PrimeNumber)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PrimeNumber::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PrimeNumber::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PrimeNumber::Clear() {
// @@protoc_insertion_point(message_clear_start:prime.PrimeNumber)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PrimeNumber::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 value = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PrimeNumber::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:prime.PrimeNumber)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 value = 1;
  if (this->_internal_value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:prime.PrimeNumber)
  return target;
}

size_t PrimeNumber::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:prime.PrimeNumber)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 value = 1;
  if (this->_internal_value() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PrimeNumber::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PrimeNumber::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PrimeNumber::GetClassData() const { return &_class_data_; }


void PrimeNumber::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PrimeNumber*>(&to_msg);
  auto& from = static_cast<const PrimeNumber&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:prime.PrimeNumber)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_value() != 0) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PrimeNumber::CopyFrom(const PrimeNumber& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:prime.PrimeNumber)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PrimeNumber::IsInitialized() const {
  return true;
}

void PrimeNumber::InternalSwap(PrimeNumber* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.value_, other->_impl_.value_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PrimeNumber::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_prime_2eproto_getter, &descriptor_table_prime_2eproto_once,
      file_level_metadata_prime_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace prime
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::prime::PrimeRequest*
Arena::CreateMaybeMessage< ::prime::PrimeRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::prime::PrimeRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::prime::PrimeResponse*
Arena::CreateMaybeMessage< ::prime::PrimeResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::prime::PrimeResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::prime::FirstPrimeRequest*
Arena::CreateMaybeMessage< ::prime::FirstPrimeRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::prime::FirstPrimeRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::prime::FirstPrimeResponse*
Arena::CreateMaybeMessage< ::prime::FirstPrimeResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::prime::FirstPrimeResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::prime::IntervalRequest*
Arena::CreateMaybeMessage< ::prime::IntervalRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::prime::IntervalRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::prime::PrimeNumber*
Arena::CreateMaybeMessage< ::prime::PrimeNumber >(Arena* arena) {
  return Arena::CreateMessageInternal< ::prime::PrimeNumber >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
