// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: prime.proto

#include "prime.pb.h"
#include "prime.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace prime {

static const char* PrimeService_method_names[] = {
  "/prime.PrimeService/IsPrime",
  "/prime.PrimeService/FirstPrime",
  "/prime.PrimeService/IntervalPrime",
};

std::unique_ptr< PrimeService::Stub> PrimeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PrimeService::Stub> stub(new PrimeService::Stub(channel, options));
  return stub;
}

PrimeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_IsPrime_(PrimeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FirstPrime_(PrimeService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_IntervalPrime_(PrimeService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status PrimeService::Stub::IsPrime(::grpc::ClientContext* context, const ::prime::PrimeRequest& request, ::prime::PrimeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::prime::PrimeRequest, ::prime::PrimeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_IsPrime_, context, request, response);
}

void PrimeService::Stub::async::IsPrime(::grpc::ClientContext* context, const ::prime::PrimeRequest* request, ::prime::PrimeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::prime::PrimeRequest, ::prime::PrimeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_IsPrime_, context, request, response, std::move(f));
}

void PrimeService::Stub::async::IsPrime(::grpc::ClientContext* context, const ::prime::PrimeRequest* request, ::prime::PrimeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_IsPrime_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::prime::PrimeResponse>* PrimeService::Stub::PrepareAsyncIsPrimeRaw(::grpc::ClientContext* context, const ::prime::PrimeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::prime::PrimeResponse, ::prime::PrimeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_IsPrime_, context, request);
}

::grpc::ClientAsyncResponseReader< ::prime::PrimeResponse>* PrimeService::Stub::AsyncIsPrimeRaw(::grpc::ClientContext* context, const ::prime::PrimeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncIsPrimeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PrimeService::Stub::FirstPrime(::grpc::ClientContext* context, const ::prime::FirstPrimeRequest& request, ::prime::FirstPrimeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::prime::FirstPrimeRequest, ::prime::FirstPrimeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FirstPrime_, context, request, response);
}

void PrimeService::Stub::async::FirstPrime(::grpc::ClientContext* context, const ::prime::FirstPrimeRequest* request, ::prime::FirstPrimeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::prime::FirstPrimeRequest, ::prime::FirstPrimeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FirstPrime_, context, request, response, std::move(f));
}

void PrimeService::Stub::async::FirstPrime(::grpc::ClientContext* context, const ::prime::FirstPrimeRequest* request, ::prime::FirstPrimeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FirstPrime_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::prime::FirstPrimeResponse>* PrimeService::Stub::PrepareAsyncFirstPrimeRaw(::grpc::ClientContext* context, const ::prime::FirstPrimeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::prime::FirstPrimeResponse, ::prime::FirstPrimeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FirstPrime_, context, request);
}

::grpc::ClientAsyncResponseReader< ::prime::FirstPrimeResponse>* PrimeService::Stub::AsyncFirstPrimeRaw(::grpc::ClientContext* context, const ::prime::FirstPrimeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFirstPrimeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::prime::PrimeNumber>* PrimeService::Stub::IntervalPrimeRaw(::grpc::ClientContext* context, const ::prime::IntervalRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::prime::PrimeNumber>::Create(channel_.get(), rpcmethod_IntervalPrime_, context, request);
}

void PrimeService::Stub::async::IntervalPrime(::grpc::ClientContext* context, const ::prime::IntervalRequest* request, ::grpc::ClientReadReactor< ::prime::PrimeNumber>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::prime::PrimeNumber>::Create(stub_->channel_.get(), stub_->rpcmethod_IntervalPrime_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::prime::PrimeNumber>* PrimeService::Stub::AsyncIntervalPrimeRaw(::grpc::ClientContext* context, const ::prime::IntervalRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::prime::PrimeNumber>::Create(channel_.get(), cq, rpcmethod_IntervalPrime_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::prime::PrimeNumber>* PrimeService::Stub::PrepareAsyncIntervalPrimeRaw(::grpc::ClientContext* context, const ::prime::IntervalRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::prime::PrimeNumber>::Create(channel_.get(), cq, rpcmethod_IntervalPrime_, context, request, false, nullptr);
}

PrimeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PrimeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PrimeService::Service, ::prime::PrimeRequest, ::prime::PrimeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PrimeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::prime::PrimeRequest* req,
             ::prime::PrimeResponse* resp) {
               return service->IsPrime(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PrimeService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PrimeService::Service, ::prime::FirstPrimeRequest, ::prime::FirstPrimeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PrimeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::prime::FirstPrimeRequest* req,
             ::prime::FirstPrimeResponse* resp) {
               return service->FirstPrime(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PrimeService_method_names[2],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< PrimeService::Service, ::prime::IntervalRequest, ::prime::PrimeNumber>(
          [](PrimeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::prime::IntervalRequest* req,
             ::grpc::ServerWriter<::prime::PrimeNumber>* writer) {
               return service->IntervalPrime(ctx, req, writer);
             }, this)));
}

PrimeService::Service::~Service() {
}

::grpc::Status PrimeService::Service::IsPrime(::grpc::ServerContext* context, const ::prime::PrimeRequest* request, ::prime::PrimeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PrimeService::Service::FirstPrime(::grpc::ServerContext* context, const ::prime::FirstPrimeRequest* request, ::prime::FirstPrimeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PrimeService::Service::IntervalPrime(::grpc::ServerContext* context, const ::prime::IntervalRequest* request, ::grpc::ServerWriter< ::prime::PrimeNumber>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace prime

